-- MySQL Script generated by MySQL Workbench
-- Fri 16 Nov 2018 12:53:05 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema puma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `puma` ;

-- -----------------------------------------------------
-- Schema puma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puma` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `puma` ;

-- -----------------------------------------------------
-- Table `puma`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puma`.`productos` ;

CREATE TABLE IF NOT EXISTS `puma`.`productos` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(255) NOT NULL,
  `prod_description` TEXT NOT NULL,
  `prod_stock` INT UNSIGNED NOT NULL,
  `prod_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prod_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
